
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mirenordonezdearce
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    //Abrimos la conexión con la BBDD, llamando al constructor.
    GestionConexion conexion = new GestionConexion();
    
    //Ponemos el model a la tabla
    DefaultTableModel modelo = new DefaultTableModel();
    
    
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents(); 
        //Inicializamos la tabla Álbum con los datos de la BBDD
        jTableAlbum.setModel(modelo);
        modelo.setColumnIdentifiers(conexion.consultaTablaAlbum());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogColumnaNuevaAlbum = new javax.swing.JDialog();
        lblColumnaCampo = new javax.swing.JLabel();
        jTextFieldColumnaAlbum = new javax.swing.JTextField();
        lblColumnaTipo = new javax.swing.JLabel();
        jComboBoxTipoAlbum = new javax.swing.JComboBox<>();
        jButtonAddUpdateAlbum = new javax.swing.JButton();
        lblTituloColumnaAlbum = new javax.swing.JLabel();
        jDialogColumnaNuevaCanciones = new javax.swing.JDialog();
        lblColumnaCampoCancion = new javax.swing.JLabel();
        jTextFieldColumnaCancion = new javax.swing.JTextField();
        lblColumnaTipo1 = new javax.swing.JLabel();
        jComboBoxTipoCancion = new javax.swing.JComboBox<>();
        jButtonAddUpdateCancion = new javax.swing.JButton();
        lblTituloColumnaAlbum1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        tabAlbum = new javax.swing.JPanel();
        jPanelTablaAlbum = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAlbum = new javax.swing.JTable();
        jPanelEstructuraAlbum = new javax.swing.JPanel();
        btnColumnaNuevaAlbum = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanelDatosAlbum = new javax.swing.JPanel();
        lblNombreAlbum = new javax.swing.JLabel();
        jTextFieldNombreAlbum = new javax.swing.JTextField();
        lblArtistaAlbum = new javax.swing.JLabel();
        jTextFieldArtistaAlbum = new javax.swing.JTextField();
        lblAnnoAlbum = new javax.swing.JLabel();
        jTextFieldAnnoAlbum = new javax.swing.JTextField();
        btnInsertarAlbum = new javax.swing.JButton();
        btnModifAlbum = new javax.swing.JButton();
        btnDeleteAlbum = new javax.swing.JButton();
        lblInfoAlbum = new javax.swing.JLabel();
        tabCanciones = new javax.swing.JPanel();
        jPanelTablaCanciones = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        salidatxtCanciones = new javax.swing.JTextArea();
        jPanelEstructuraCanciones = new javax.swing.JPanel();
        btnColumnaNuevaCancion = new javax.swing.JButton();
        btnDeleteColumnaCancion = new javax.swing.JButton();
        jPanelDatosAlbum1 = new javax.swing.JPanel();
        lblTituloCancion = new javax.swing.JLabel();
        jTextFieldTituloCancion = new javax.swing.JTextField();
        lblDuracionCancion = new javax.swing.JLabel();
        jTextFieldDuracionCancion = new javax.swing.JTextField();
        lblAlbumCancion = new javax.swing.JLabel();
        btnInsertarCancion = new javax.swing.JButton();
        btnModifCancion = new javax.swing.JButton();
        btnDeleteCancion = new javax.swing.JButton();
        lblInfoCanciones = new javax.swing.JLabel();
        jComboBoxAlbumCancion = new javax.swing.JComboBox<>();

        jDialogColumnaNuevaAlbum.setBounds(new java.awt.Rectangle(0, 25, 285, 240));

        lblColumnaCampo.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        lblColumnaCampo.setText("Escribe el nombre del nuevo campo a añadir.");

        lblColumnaTipo.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        lblColumnaTipo.setText("Seleccione el tipo de dato que se va a añadir.");

        jComboBoxTipoAlbum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Numérico", "Alfanumérico", "Alfabético" }));

        jButtonAddUpdateAlbum.setText("Añadir y actualizar tabla");
        jButtonAddUpdateAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddUpdateAlbumActionPerformed(evt);
            }
        });

        lblTituloColumnaAlbum.setText("Insertar una nueva columna a la tabla Álbum");

        javax.swing.GroupLayout jDialogColumnaNuevaAlbumLayout = new javax.swing.GroupLayout(jDialogColumnaNuevaAlbum.getContentPane());
        jDialogColumnaNuevaAlbum.getContentPane().setLayout(jDialogColumnaNuevaAlbumLayout);
        jDialogColumnaNuevaAlbumLayout.setHorizontalGroup(
            jDialogColumnaNuevaAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogColumnaNuevaAlbumLayout.createSequentialGroup()
                .addGroup(jDialogColumnaNuevaAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloColumnaAlbum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jDialogColumnaNuevaAlbumLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblColumnaCampo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jTextFieldColumnaAlbum, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jDialogColumnaNuevaAlbumLayout.createSequentialGroup()
                        .addGroup(jDialogColumnaNuevaAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDialogColumnaNuevaAlbumLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblColumnaTipo))
                            .addComponent(jComboBoxTipoAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jDialogColumnaNuevaAlbumLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jButtonAddUpdateAlbum)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialogColumnaNuevaAlbumLayout.setVerticalGroup(
            jDialogColumnaNuevaAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogColumnaNuevaAlbumLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloColumnaAlbum)
                .addGap(21, 21, 21)
                .addComponent(lblColumnaCampo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldColumnaAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblColumnaTipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxTipoAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jButtonAddUpdateAlbum)
                .addGap(33, 33, 33))
        );

        jDialogColumnaNuevaCanciones.setBackground(new java.awt.Color(0, 153, 153));
        jDialogColumnaNuevaCanciones.setBounds(new java.awt.Rectangle(0, 25, 310, 240));

        lblColumnaCampoCancion.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        lblColumnaCampoCancion.setText("Escribe el nombre del nuevo campo a añadir.");

        lblColumnaTipo1.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        lblColumnaTipo1.setText("Seleccione el tipo de dato que se va a añadir.");

        jComboBoxTipoCancion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Numérico", "Alfanumérico", "Alfabético" }));

        jButtonAddUpdateCancion.setText("Añadir y actualizar tabla");
        jButtonAddUpdateCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddUpdateCancionActionPerformed(evt);
            }
        });

        lblTituloColumnaAlbum1.setText("Insertar una nueva columna a la tabla Canciones");

        javax.swing.GroupLayout jDialogColumnaNuevaCancionesLayout = new javax.swing.GroupLayout(jDialogColumnaNuevaCanciones.getContentPane());
        jDialogColumnaNuevaCanciones.getContentPane().setLayout(jDialogColumnaNuevaCancionesLayout);
        jDialogColumnaNuevaCancionesLayout.setHorizontalGroup(
            jDialogColumnaNuevaCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogColumnaNuevaCancionesLayout.createSequentialGroup()
                .addGroup(jDialogColumnaNuevaCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloColumnaAlbum1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jDialogColumnaNuevaCancionesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblColumnaCampoCancion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jTextFieldColumnaCancion, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jDialogColumnaNuevaCancionesLayout.createSequentialGroup()
                        .addGroup(jDialogColumnaNuevaCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDialogColumnaNuevaCancionesLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblColumnaTipo1))
                            .addComponent(jComboBoxTipoCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jDialogColumnaNuevaCancionesLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jButtonAddUpdateCancion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialogColumnaNuevaCancionesLayout.setVerticalGroup(
            jDialogColumnaNuevaCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogColumnaNuevaCancionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloColumnaAlbum1)
                .addGap(21, 21, 21)
                .addComponent(lblColumnaCampoCancion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldColumnaCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblColumnaTipo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxTipoCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jButtonAddUpdateCancion)
                .addGap(33, 33, 33))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(221, 238, 244));

        jTabbedPane1.setBackground(new java.awt.Color(219, 238, 248));

        tabAlbum.setBackground(new java.awt.Color(0, 153, 153));

        jPanelTablaAlbum.setBackground(new java.awt.Color(0, 153, 153));

        jTableAlbum.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableAlbum);

        javax.swing.GroupLayout jPanelTablaAlbumLayout = new javax.swing.GroupLayout(jPanelTablaAlbum);
        jPanelTablaAlbum.setLayout(jPanelTablaAlbumLayout);
        jPanelTablaAlbumLayout.setHorizontalGroup(
            jPanelTablaAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTablaAlbumLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanelTablaAlbumLayout.setVerticalGroup(
            jPanelTablaAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTablaAlbumLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelEstructuraAlbum.setBackground(new java.awt.Color(0, 153, 153));
        jPanelEstructuraAlbum.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 204, 204), null));

        btnColumnaNuevaAlbum.setText("Añadir columna nueva");
        btnColumnaNuevaAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColumnaNuevaAlbumActionPerformed(evt);
            }
        });

        jButton1.setText("Eliminar columna existente");

        javax.swing.GroupLayout jPanelEstructuraAlbumLayout = new javax.swing.GroupLayout(jPanelEstructuraAlbum);
        jPanelEstructuraAlbum.setLayout(jPanelEstructuraAlbumLayout);
        jPanelEstructuraAlbumLayout.setHorizontalGroup(
            jPanelEstructuraAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEstructuraAlbumLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEstructuraAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnColumnaNuevaAlbum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelEstructuraAlbumLayout.setVerticalGroup(
            jPanelEstructuraAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEstructuraAlbumLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnColumnaNuevaAlbum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jPanelDatosAlbum.setBackground(new java.awt.Color(0, 153, 153));
        jPanelDatosAlbum.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 204, 204), null));

        lblNombreAlbum.setText("NOMBRE");

        lblArtistaAlbum.setText("ARTISTA");

        lblAnnoAlbum.setText("AÑO PUBLICACIÓN");

        btnInsertarAlbum.setText("Insertar");
        btnInsertarAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarAlbumActionPerformed(evt);
            }
        });

        btnModifAlbum.setText("Modificar");

        btnDeleteAlbum.setText("Eliminar");

        lblInfoAlbum.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        lblInfoAlbum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanelDatosAlbumLayout = new javax.swing.GroupLayout(jPanelDatosAlbum);
        jPanelDatosAlbum.setLayout(jPanelDatosAlbumLayout);
        jPanelDatosAlbumLayout.setHorizontalGroup(
            jPanelDatosAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosAlbumLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblInfoAlbum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelDatosAlbumLayout.createSequentialGroup()
                        .addGroup(jPanelDatosAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblAnnoAlbum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblArtistaAlbum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNombreAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnInsertarAlbum, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelDatosAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldNombreAlbum)
                            .addComponent(jTextFieldArtistaAlbum)
                            .addComponent(jTextFieldAnnoAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnModifAlbum))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 194, Short.MAX_VALUE)
                .addComponent(btnDeleteAlbum))
        );
        jPanelDatosAlbumLayout.setVerticalGroup(
            jPanelDatosAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosAlbumLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreAlbum)
                    .addComponent(jTextFieldNombreAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblArtistaAlbum)
                    .addComponent(jTextFieldArtistaAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnnoAlbum)
                    .addComponent(jTextFieldAnnoAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInfoAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsertarAlbum)
                    .addComponent(btnModifAlbum)
                    .addComponent(btnDeleteAlbum))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout tabAlbumLayout = new javax.swing.GroupLayout(tabAlbum);
        tabAlbum.setLayout(tabAlbumLayout);
        tabAlbumLayout.setHorizontalGroup(
            tabAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTablaAlbum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(tabAlbumLayout.createSequentialGroup()
                .addComponent(jPanelEstructuraAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelDatosAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        tabAlbumLayout.setVerticalGroup(
            tabAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabAlbumLayout.createSequentialGroup()
                .addComponent(jPanelTablaAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelEstructuraAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelDatosAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Álbumes", tabAlbum);

        tabCanciones.setBackground(new java.awt.Color(0, 153, 153));

        jPanelTablaCanciones.setBackground(new java.awt.Color(0, 153, 153));

        salidatxtCanciones.setEditable(false);
        salidatxtCanciones.setColumns(20);
        salidatxtCanciones.setRows(5);
        jScrollPane3.setViewportView(salidatxtCanciones);

        javax.swing.GroupLayout jPanelTablaCancionesLayout = new javax.swing.GroupLayout(jPanelTablaCanciones);
        jPanelTablaCanciones.setLayout(jPanelTablaCancionesLayout);
        jPanelTablaCancionesLayout.setHorizontalGroup(
            jPanelTablaCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTablaCancionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanelTablaCancionesLayout.setVerticalGroup(
            jPanelTablaCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTablaCancionesLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelEstructuraCanciones.setBackground(new java.awt.Color(0, 153, 153));
        jPanelEstructuraCanciones.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 204, 204), null));

        btnColumnaNuevaCancion.setText("Añadir columna nueva");
        btnColumnaNuevaCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColumnaNuevaCancionActionPerformed(evt);
            }
        });

        btnDeleteColumnaCancion.setText("Eliminar columna existente");

        javax.swing.GroupLayout jPanelEstructuraCancionesLayout = new javax.swing.GroupLayout(jPanelEstructuraCanciones);
        jPanelEstructuraCanciones.setLayout(jPanelEstructuraCancionesLayout);
        jPanelEstructuraCancionesLayout.setHorizontalGroup(
            jPanelEstructuraCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEstructuraCancionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEstructuraCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnColumnaNuevaCancion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDeleteColumnaCancion, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelEstructuraCancionesLayout.setVerticalGroup(
            jPanelEstructuraCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEstructuraCancionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnColumnaNuevaCancion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDeleteColumnaCancion)
                .addContainerGap())
        );

        jPanelDatosAlbum1.setBackground(new java.awt.Color(0, 153, 153));
        jPanelDatosAlbum1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 204, 204), null));

        lblTituloCancion.setText("NOMBRE");

        lblDuracionCancion.setText("ARTISTA");

        lblAlbumCancion.setText("AÑO PUBLICACIÓN");

        btnInsertarCancion.setText("Insertar");
        btnInsertarCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarCancionActionPerformed(evt);
            }
        });

        btnModifCancion.setText("Modificar");

        btnDeleteCancion.setText("Eliminar");

        lblInfoCanciones.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        lblInfoCanciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInfoCanciones.setBounds(new java.awt.Rectangle(0, 0, 45, 16));
        lblInfoCanciones.setMinimumSize(new java.awt.Dimension(45, 16));

        jComboBoxAlbumCancion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanelDatosAlbum1Layout = new javax.swing.GroupLayout(jPanelDatosAlbum1);
        jPanelDatosAlbum1.setLayout(jPanelDatosAlbum1Layout);
        jPanelDatosAlbum1Layout.setHorizontalGroup(
            jPanelDatosAlbum1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosAlbum1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosAlbum1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblInfoCanciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelDatosAlbum1Layout.createSequentialGroup()
                        .addGroup(jPanelDatosAlbum1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblAlbumCancion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDuracionCancion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTituloCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnInsertarCancion, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelDatosAlbum1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldTituloCancion, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                            .addComponent(jTextFieldDuracionCancion)
                            .addComponent(btnModifCancion)
                            .addComponent(jComboBoxAlbumCancion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 194, Short.MAX_VALUE)
                .addComponent(btnDeleteCancion))
        );
        jPanelDatosAlbum1Layout.setVerticalGroup(
            jPanelDatosAlbum1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosAlbum1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosAlbum1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTituloCancion)
                    .addComponent(jTextFieldTituloCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosAlbum1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDuracionCancion)
                    .addComponent(jTextFieldDuracionCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosAlbum1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAlbumCancion)
                    .addComponent(jComboBoxAlbumCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInfoCanciones, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosAlbum1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsertarCancion)
                    .addComponent(btnModifCancion)
                    .addComponent(btnDeleteCancion))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout tabCancionesLayout = new javax.swing.GroupLayout(tabCanciones);
        tabCanciones.setLayout(tabCancionesLayout);
        tabCancionesLayout.setHorizontalGroup(
            tabCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTablaCanciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(tabCancionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelEstructuraCanciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelDatosAlbum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        tabCancionesLayout.setVerticalGroup(
            tabCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCancionesLayout.createSequentialGroup()
                .addComponent(jPanelTablaCanciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelDatosAlbum1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelEstructuraCanciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Canciones", tabCanciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddUpdateAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddUpdateAlbumActionPerformed
        //Ejecuta el método que añade la columna
        conexion.annadirColumnaAlbum(jTextFieldColumnaAlbum.getText(), jComboBoxTipoAlbum.getSelectedItem().toString());
    }//GEN-LAST:event_jButtonAddUpdateAlbumActionPerformed

    private void jButtonAddUpdateCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddUpdateCancionActionPerformed
        //Ejecuta el método que añade la columna
        conexion.annadirColumnaCanciones(jTextFieldColumnaAlbum.getText(), jComboBoxTipoAlbum.getSelectedItem().toString());
    }//GEN-LAST:event_jButtonAddUpdateCancionActionPerformed

    private void btnInsertarAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarAlbumActionPerformed
        //Insertar un nuevo álbum a la tabla Álbum
        conexion.insertarDatosAlbum(jTextFieldNombreAlbum.getText(), jTextFieldArtistaAlbum.getText(), jTextFieldAnnoAlbum.getText());
    }//GEN-LAST:event_btnInsertarAlbumActionPerformed

    private void btnColumnaNuevaAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColumnaNuevaAlbumActionPerformed
        //Abre el dialog para introducir una nueva columna a la tabla Álbum
        jDialogColumnaNuevaAlbum.setVisible(true);
    }//GEN-LAST:event_btnColumnaNuevaAlbumActionPerformed

    private void btnColumnaNuevaCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColumnaNuevaCancionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnColumnaNuevaCancionActionPerformed

    private void btnInsertarCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarCancionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInsertarCancionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnColumnaNuevaAlbum;
    private javax.swing.JButton btnColumnaNuevaCancion;
    private javax.swing.JButton btnDeleteAlbum;
    private javax.swing.JButton btnDeleteCancion;
    private javax.swing.JButton btnDeleteColumnaCancion;
    private javax.swing.JButton btnInsertarAlbum;
    private javax.swing.JButton btnInsertarCancion;
    private javax.swing.JButton btnModifAlbum;
    private javax.swing.JButton btnModifCancion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAddUpdateAlbum;
    private javax.swing.JButton jButtonAddUpdateCancion;
    private javax.swing.JComboBox<String> jComboBoxAlbumCancion;
    private javax.swing.JComboBox<String> jComboBoxTipoAlbum;
    private javax.swing.JComboBox<String> jComboBoxTipoCancion;
    private javax.swing.JDialog jDialogColumnaNuevaAlbum;
    private javax.swing.JDialog jDialogColumnaNuevaCanciones;
    private javax.swing.JPanel jPanelDatosAlbum;
    private javax.swing.JPanel jPanelDatosAlbum1;
    private javax.swing.JPanel jPanelEstructuraAlbum;
    private javax.swing.JPanel jPanelEstructuraCanciones;
    private javax.swing.JPanel jPanelTablaAlbum;
    private javax.swing.JPanel jPanelTablaCanciones;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableAlbum;
    private javax.swing.JTextField jTextFieldAnnoAlbum;
    private javax.swing.JTextField jTextFieldArtistaAlbum;
    private javax.swing.JTextField jTextFieldColumnaAlbum;
    private javax.swing.JTextField jTextFieldColumnaCancion;
    private javax.swing.JTextField jTextFieldDuracionCancion;
    private javax.swing.JTextField jTextFieldNombreAlbum;
    private javax.swing.JTextField jTextFieldTituloCancion;
    private javax.swing.JLabel lblAlbumCancion;
    private javax.swing.JLabel lblAnnoAlbum;
    private javax.swing.JLabel lblArtistaAlbum;
    private javax.swing.JLabel lblColumnaCampo;
    private javax.swing.JLabel lblColumnaCampoCancion;
    private javax.swing.JLabel lblColumnaTipo;
    private javax.swing.JLabel lblColumnaTipo1;
    private javax.swing.JLabel lblDuracionCancion;
    private javax.swing.JLabel lblInfoAlbum;
    private javax.swing.JLabel lblInfoCanciones;
    private javax.swing.JLabel lblNombreAlbum;
    private javax.swing.JLabel lblTituloCancion;
    private javax.swing.JLabel lblTituloColumnaAlbum;
    private javax.swing.JLabel lblTituloColumnaAlbum1;
    private javax.swing.JTextArea salidatxtCanciones;
    private javax.swing.JPanel tabAlbum;
    private javax.swing.JPanel tabCanciones;
    // End of variables declaration//GEN-END:variables
}
